# Travis Configuration
stages:
  - name: test
    if: branch != master
  - name: build
    if: branch IN (master, develop)
  - name: package
    if: branch IN (master, develop)
  - name: integration
    if: branch IN (master, develop)
  - name: publish
    if: branch IN (master, develop)

jobs:
  include:
    - stage: test
      name: "ruby-project test"
      language: ruby
      rvm: 2.5
      install:
        - make ruby_install
      script:
        - make ruby_test

    - stage: test
      name: "java-project test"
      language: java
      jdk: openjdk8
      install:
        - make java_install
      script:
        - make java_test

    - stage: test
      name: "nodejs-project test"
      language: node_js
      node_js: lts/dubnium
      install:
        - make nodejs_install
      script:
        - make nodejs_test


    - stage: build
      name: "nodejs-project build"
      language: node_js
      node_js: lts/dubnium
      install:
        - make nodejs_install
      script:
        - make nodejs_build


    - stage: package
      name: "java-project package"
      language: java
      jdk: openjdk8
      install:
        - make java_install
      script:
        - make java_package

    - stage: package
      name: "nodejs-project package"
      language: node_js
      node_js: lts/dubnium
      install:
        - make nodejs_install
      script:
        - make nodejs_package


    - stage: integration
      name: "ruby-project integration"
      language: ruby
      rvm: 2.5
      install:
        - make ruby_install
      script:
        - make ruby_integration

    - stage: integration
      name: "java-project integration"
      language: java
      jdk: openjdk8
      install:
        - make java_install
      script:
        - make java_integration

    - stage: integration
      name: "nodejs-project integration"
      language: node_js
      node_js: lts/dubnium
      install:
        - make nodejs_install
      script:
        - make nodejs_integration


    - stage: publish
      name: "ruby-project publish"
      language: ruby
      rvm: 2.5
      install:
        - make ruby_install
      script:
        - make ruby_publish

    - stage: publish
      name: "java-project publish"
      language: java
      jdk: openjdk8
      install:
        - make java_install
      script:
        - make java_publish

    - stage: publish
      name: "nodejs-project publish"
      language: node_js
      node_js: lts/dubnium
      install:
        - make nodejs_install
      script:
        - make nodejs_publish
