# Travis Configuration
stages:
  - name: test
    if: branch != master AND (NOT(branch = develop AND type = push))
  - name: build
    if: branch = master AND type != push
  - name: package
    if: branch = master AND type != push
  - name: integration
    if: branch = master AND type != push
  - name: publish
    if: branch = master AND type = push

jobs:
  include:
    - stage: test
      name: "ruby-project test"
      language: ruby
      rvm: 2.5
      install:
        - make PROJECT=ruby install
      script:
        - make PROJECT=ruby test

    - stage: test
      name: "java-project test"
      language: java
      jdk: openjdk8
      install:
        - make PROJECT=java install
      script:
        - make PROJECT=java test

    - stage: test
      name: "nodejs-project test"
      language: node_js
      node_js: lts/dubnium
      install:
        - make PROJECT=nodejs install
      script:
        - make PROJECT=nodejs test


    - stage: build
      name: "nodejs-project build"
      language: node_js
      node_js: lts/dubnium
      install:
        - make PROJECT=nodejs install
      script:
        - make PROJECT=nodejs build


    - stage: package
      name: "java-project package"
      language: java
      jdk: openjdk8
      install:
        - make PROJECT=java install
      script:
        - make PROJECT=java package

    - stage: package
      name: "nodejs-project package"
      language: node_js
      node_js: lts/dubnium
      install:
        - make PROJECT=nodejs install
      script:
        - make PROJECT=nodejs package


    - stage: integration
      name: "ruby-project integration"
      language: ruby
      rvm: 2.5
      install:
        - make PROJECT=ruby install
      script:
        - make PROJECT=ruby integration

    - stage: integration
      name: "java-project integration"
      language: java
      jdk: openjdk8
      install:
        - make PROJECT=java install
      script:
        - make PROJECT=java integration

    - stage: integration
      name: "nodejs-project integration"
      language: node_js
      node_js: lts/dubnium
      install:
        - make PROJECT=nodejs install
      script:
        - make PROJECT=nodejs integration


    - stage: publish
      name: "ruby-project publish"
      language: ruby
      rvm: 2.5
      install:
        - make PROJECT=ruby install
      script:
        - make PROJECT=ruby publish

    - stage: publish
      name: "java-project publish"
      language: java
      jdk: openjdk8
      install:
        - make PROJECT=java install
      script:
        - make PROJECT=java publish

    - stage: publish
      name: "nodejs-project publish"
      language: node_js
      node_js: lts/dubnium
      install:
        - make PROJECT=nodejs install
      script:
        - make PROJECT=nodejs publish
